// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: server/api/spellingbee/v1/manager.proto

package managerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_server_api_spellingbee_v1_manager_proto_rawDescGZIP(), []int{0}
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Letters       string                 `protobuf:"bytes,2,opt,name=letters,proto3" json:"letters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_server_api_spellingbee_v1_manager_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateGameResponse) GetLetters() string {
	if x != nil {
		return x.Letters
	}
	return ""
}

type EndGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndGameRequest) Reset() {
	*x = EndGameRequest{}
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndGameRequest) ProtoMessage() {}

func (x *EndGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndGameRequest.ProtoReflect.Descriptor instead.
func (*EndGameRequest) Descriptor() ([]byte, []int) {
	return file_server_api_spellingbee_v1_manager_proto_rawDescGZIP(), []int{2}
}

func (x *EndGameRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EndGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndGameResponse) Reset() {
	*x = EndGameResponse{}
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndGameResponse) ProtoMessage() {}

func (x *EndGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndGameResponse.ProtoReflect.Descriptor instead.
func (*EndGameResponse) Descriptor() ([]byte, []int) {
	return file_server_api_spellingbee_v1_manager_proto_rawDescGZIP(), []int{3}
}

func (x *EndGameResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_server_api_spellingbee_v1_manager_proto_rawDescGZIP(), []int{4}
}

func (x *ScoreRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_server_api_spellingbee_v1_manager_proto_rawDescGZIP(), []int{5}
}

func (x *ScoreResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Guess         string                 `protobuf:"bytes,2,opt,name=guess,proto3" json:"guess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_server_api_spellingbee_v1_manager_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubmitRequest) GetGuess() string {
	if x != nil {
		return x.Guess
	}
	return ""
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_spellingbee_v1_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_server_api_spellingbee_v1_manager_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_server_api_spellingbee_v1_manager_proto protoreflect.FileDescriptor

const file_server_api_spellingbee_v1_manager_proto_rawDesc = "" +
	"\n" +
	"'server/api/spellingbee/v1/manager.proto\x12\x0espellingbee.v1\"\x13\n" +
	"\x11CreateGameRequest\">\n" +
	"\x12CreateGameResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aletters\x18\x02 \x01(\tR\aletters\" \n" +
	"\x0eEndGameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"'\n" +
	"\x0fEndGameResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\"\x1e\n" +
	"\fScoreRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"%\n" +
	"\rScoreResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\"5\n" +
	"\rSubmitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05guess\x18\x02 \x01(\tR\x05guess\"@\n" +
	"\x0eSubmitResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score2\xb9\x02\n" +
	"\aManager\x12S\n" +
	"\n" +
	"CreateGame\x12!.spellingbee.v1.CreateGameRequest\x1a\".spellingbee.v1.CreateGameResponse\x12J\n" +
	"\aEndGame\x12\x1e.spellingbee.v1.EndGameRequest\x1a\x1f.spellingbee.v1.EndGameResponse\x12D\n" +
	"\x05Score\x12\x1c.spellingbee.v1.ScoreRequest\x1a\x1d.spellingbee.v1.ScoreResponse\x12G\n" +
	"\x06Submit\x12\x1d.spellingbee.v1.SubmitRequest\x1a\x1e.spellingbee.v1.SubmitResponseB0Z.spelling-bee-game/api/spellingbee/v1;managerpbb\x06proto3"

var (
	file_server_api_spellingbee_v1_manager_proto_rawDescOnce sync.Once
	file_server_api_spellingbee_v1_manager_proto_rawDescData []byte
)

func file_server_api_spellingbee_v1_manager_proto_rawDescGZIP() []byte {
	file_server_api_spellingbee_v1_manager_proto_rawDescOnce.Do(func() {
		file_server_api_spellingbee_v1_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_api_spellingbee_v1_manager_proto_rawDesc), len(file_server_api_spellingbee_v1_manager_proto_rawDesc)))
	})
	return file_server_api_spellingbee_v1_manager_proto_rawDescData
}

var file_server_api_spellingbee_v1_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_server_api_spellingbee_v1_manager_proto_goTypes = []any{
	(*CreateGameRequest)(nil),  // 0: spellingbee.v1.CreateGameRequest
	(*CreateGameResponse)(nil), // 1: spellingbee.v1.CreateGameResponse
	(*EndGameRequest)(nil),     // 2: spellingbee.v1.EndGameRequest
	(*EndGameResponse)(nil),    // 3: spellingbee.v1.EndGameResponse
	(*ScoreRequest)(nil),       // 4: spellingbee.v1.ScoreRequest
	(*ScoreResponse)(nil),      // 5: spellingbee.v1.ScoreResponse
	(*SubmitRequest)(nil),      // 6: spellingbee.v1.SubmitRequest
	(*SubmitResponse)(nil),     // 7: spellingbee.v1.SubmitResponse
}
var file_server_api_spellingbee_v1_manager_proto_depIdxs = []int32{
	0, // 0: spellingbee.v1.Manager.CreateGame:input_type -> spellingbee.v1.CreateGameRequest
	2, // 1: spellingbee.v1.Manager.EndGame:input_type -> spellingbee.v1.EndGameRequest
	4, // 2: spellingbee.v1.Manager.Score:input_type -> spellingbee.v1.ScoreRequest
	6, // 3: spellingbee.v1.Manager.Submit:input_type -> spellingbee.v1.SubmitRequest
	1, // 4: spellingbee.v1.Manager.CreateGame:output_type -> spellingbee.v1.CreateGameResponse
	3, // 5: spellingbee.v1.Manager.EndGame:output_type -> spellingbee.v1.EndGameResponse
	5, // 6: spellingbee.v1.Manager.Score:output_type -> spellingbee.v1.ScoreResponse
	7, // 7: spellingbee.v1.Manager.Submit:output_type -> spellingbee.v1.SubmitResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_api_spellingbee_v1_manager_proto_init() }
func file_server_api_spellingbee_v1_manager_proto_init() {
	if File_server_api_spellingbee_v1_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_api_spellingbee_v1_manager_proto_rawDesc), len(file_server_api_spellingbee_v1_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_api_spellingbee_v1_manager_proto_goTypes,
		DependencyIndexes: file_server_api_spellingbee_v1_manager_proto_depIdxs,
		MessageInfos:      file_server_api_spellingbee_v1_manager_proto_msgTypes,
	}.Build()
	File_server_api_spellingbee_v1_manager_proto = out.File
	file_server_api_spellingbee_v1_manager_proto_goTypes = nil
	file_server_api_spellingbee_v1_manager_proto_depIdxs = nil
}
